In [1]:
import numpy as np

# Define the activation function
def step_function(x):
    return np.where(x >= 0, 1, -1)

# Define the perceptron class
class Perceptron:
    def __init__(self, input_size):
        self.weights = np.random.uniform(-2, 2, input_size)  # Initialize weights randomly in range (-2, 2)

    def train(self, X, y, learning_rate, epochs):
        for _ in range(epochs):
            for xi, target in zip(X, y):
                output = self.predict(xi)
                error = target - output
                self.weights += learning_rate * error * xi

    def predict(self, X):
        activation = np.dot(X, self.weights)
        return step_function(activation)

In [2]:
# Define the Boolean functions
def NOT(x):
    return 1 if x == 0 else -1

def OR(x1, x2):
    return 1 if x1 or x2 else -1

def AND(x1, x2):
    return 1 if x1 and x2 else -1

def NOR(x1, x2):
    return 1 if not (x1 or x2) else -1

def NAND(x1, x2):
    return 1 if not (x1 and x2) else -1

In [3]:
# Define the training data for each Boolean function
X_NOT = np.array([[0]])
y_NOT = np.array([NOT(0)])

X_OR = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y_OR = np.array([OR(0, 0), OR(0, 1), OR(1, 0), OR(1, 1)])

X_AND = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y_AND = np.array([AND(0, 0), AND(0, 1), AND(1, 0), AND(1, 1)])

X_NOR = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y_NOR = np.array([NOR(0, 0), NOR(0, 1), NOR(1, 0), NOR(1, 1)])

X_NAND = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y_NAND = np.array([NAND(0, 0), NAND(0, 1), NAND(1, 0), NAND(1, 1)])

In [4]:

# Train perceptrons for each Boolean function
perceptron_NOT = Perceptron(1)
perceptron_NOT.train(X_NOT, y_NOT, 0.1, 100)

perceptron_OR = Perceptron(2)
perceptron_OR.train(X_OR, y_OR, 0.1, 100)

perceptron_AND = Perceptron(2)
perceptron_AND.train(X_AND, y_AND, 0.1, 100)

perceptron_NOR = Perceptron(2)
perceptron_NOR.train(X_NOR, y_NOR, 0.1, 100)

perceptron_NAND = Perceptron(2)
perceptron_NAND.train(X_NAND, y_NAND, 0.1, 100)



In [5]:
# Print learned weights for each perceptron
print("Weights for NOT function: ", perceptron_NOT.weights)
print("Weights for OR function: ", perceptron_OR.weights)
print("Weights for AND function: ", perceptron_AND.weights)
print("Weights for NOR function: ", perceptron_NOR.weights)
print("Weights for NAND function: ", perceptron_NAND.weights)

Weights for NOT function:  [0.37302155]
Weights for OR function:  [0.12526447 0.89896046]
Weights for AND function:  [0.18074473 0.11750488]
Weights for NOR function:  [-0.00696938 -1.3996362 ]
Weights for NAND function:  [-0.07849623 -0.16874202]


### Prediction

In [9]:
perceptron_OR.predict(X_OR)

array([1, 1, 1, 1])

In [10]:
perceptron_AND.predict(X_AND)

array([1, 1, 1, 1])

### Verifying the result for AND

In [11]:
perceptron_AND.weights

array([0.18074473, 0.11750488])

In [12]:
AND(perceptron_AND.weights[0]*0,perceptron_AND.weights[1]*1)

-1

In [13]:
AND(perceptron_AND.weights[0]*0,perceptron_AND.weights[1]*0)

-1

In [14]:
AND(perceptron_AND.weights[0]*1,perceptron_AND.weights[1]*0)

-1

In [15]:
AND(perceptron_AND.weights[0]*1,perceptron_AND.weights[1]*1)

1