In [ ]:
from tensorflow.keras.preprocessing.text import one_hot

In [ ]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [ ]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [ ]:
### Vocabulary size
voc_size=10000

In [ ]:
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[4329, 8368, 556, 6208], [4329, 8368, 556, 8325], [4329, 7425, 556, 8027], [4644, 9928, 6825, 8661, 2303], [4644, 9928, 6825, 8661, 8626], [7229, 4329, 5691, 556, 5794], [5612, 4009, 4423, 8661]]


In [ ]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [ ]:
import numpy as np
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 4329 8368  556 6208]
 [   0    0    0    0 4329 8368  556 8325]
 [   0    0    0    0 4329 7425  556 8027]
 [   0    0    0 4644 9928 6825 8661 2303]
 [   0    0    0 4644 9928 6825 8661 8626]
 [   0    0    0 7229 4329 5691  556 5794]
 [   0    0    0    0 5612 4009 4423 8661]]


In [ ]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [ ]:
model= Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))

In [ ]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_2 (Embedding)     (None, 8, 10)             100000    
                                                                 
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [ ]:
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 38ms/step
[[[-0.00610081  0.02629677  0.00429667  0.00865048  0.0098931
   -0.02278913  0.00326608 -0.04358968  0.04009051  0.02882074]
  [-0.00610081  0.02629677  0.00429667  0.00865048  0.0098931
   -0.02278913  0.00326608 -0.04358968  0.04009051  0.02882074]
  [-0.00610081  0.02629677  0.00429667  0.00865048  0.0098931
   -0.02278913  0.00326608 -0.04358968  0.04009051  0.02882074]
  [-0.00610081  0.02629677  0.00429667  0.00865048  0.0098931
   -0.02278913  0.00326608 -0.04358968  0.04009051  0.02882074]
  [ 0.0194344  -0.0431533  -0.00038391  0.03734955  0.0472532
   -0.04068986 -0.0340945  -0.01894933  0.04383465 -0.00318904]
  [ 0.0122113   0.02769455  0.01097989  0.02228211  0.03635528
    0.03989668 -0.03939449  0.03144273 -0.04324513 -0.01240076]
  [ 0.04556099  0.04253385 -0.01592389  0.02728963  0.04696004
   -0.04210971  0.02228889  0.00118555 -0.00912695 -0.0272615 ]
  [ 0.01429329 -0.01524056 -0.0427915   0.0092846  -0.01476968
 

In [ ]:
print(embedded_docs[1])

[   0    0    0    0 4329 8368  556 8325]


In [ ]:
print(model.predict(embedded_docs)[0])

1/1 [==============================] - 0s 19ms/step
[[-0.00610081  0.02629677  0.00429667  0.00865048  0.0098931  -0.02278913
   0.00326608 -0.04358968  0.04009051  0.02882074]
 [-0.00610081  0.02629677  0.00429667  0.00865048  0.0098931  -0.02278913
   0.00326608 -0.04358968  0.04009051  0.02882074]
 [-0.00610081  0.02629677  0.00429667  0.00865048  0.0098931  -0.02278913
   0.00326608 -0.04358968  0.04009051  0.02882074]
 [-0.00610081  0.02629677  0.00429667  0.00865048  0.0098931  -0.02278913
   0.00326608 -0.04358968  0.04009051  0.02882074]
 [ 0.0194344  -0.0431533  -0.00038391  0.03734955  0.0472532  -0.04068986
  -0.0340945  -0.01894933  0.04383465 -0.00318904]
 [ 0.0122113   0.02769455  0.01097989  0.02228211  0.03635528  0.03989668
  -0.03939449  0.03144273 -0.04324513 -0.01240076]
 [ 0.04556099  0.04253385 -0.01592389  0.02728963  0.04696004 -0.04210971
   0.02228889  0.00118555 -0.00912695 -0.0272615 ]
 [ 0.01429329 -0.01524056 -0.0427915   0.0092846  -0.01476968 -0.03964401