In [1]:
from numpy import array
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Flatten,Embedding,Dense,LSTM

In [2]:
# Define 10 restaurant reviews
reviews =[
          'Never coming back!',
          'horrible service',
          'rude waitress',
          'cold food',
          'horrible food!',
          'awesome',
          'awesome services!',
          'rocks',
          'poor work',
          'couldn\'t have done better'
]
#Define labels
labels = array([1,1,1,1,1,0,0,0,0,0])

In [3]:
Vocab_size = 50
encoded_reviews = [one_hot(d,Vocab_size) for d in reviews]
print(f'encoded reviews: {encoded_reviews}')

encoded reviews: [[11, 34, 49], [31, 3], [31, 42], [16, 48], [31, 48], [13], [13, 20], [8], [41, 14], [4, 36, 15, 22]]


In [4]:
max_length = 4
padded_reviews = pad_sequences(encoded_reviews,maxlen=max_length,padding='post')
print(padded_reviews)

[[11 34 49  0]
 [31  3  0  0]
 [31 42  0  0]
 [16 48  0  0]
 [31 48  0  0]
 [13  0  0  0]
 [13 20  0  0]
 [ 8  0  0  0]
 [41 14  0  0]
 [ 4 36 15 22]]


In [5]:
model = Sequential()
embedding_layer = Embedding(input_dim=Vocab_size,output_dim=8,input_length=max_length)
model.add(embedding_layer)
model.add(LSTM(50, dropout=0.2, recurrent_dropout=0.2))
#model.add(Flatten())
model.add(Dense(1,activation='sigmoid'))
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['acc'])
print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 4, 8)              400       
                                                                 
 lstm (LSTM)                 (None, 50)                11800     
                                                                 
 dense (Dense)               (None, 1)                 51        
                                                                 
Total params: 12,251
Trainable params: 12,251
Non-trainable params: 0
_________________________________________________________________
None


In [6]:
model.fit(padded_reviews,labels,epochs=100,verbose=2)

Epoch 1/100
1/1 - 4s - loss: 0.6927 - acc: 0.6000 - 4s/epoch - 4s/step
Epoch 2/100
1/1 - 0s - loss: 0.6930 - acc: 0.5000 - 13ms/epoch - 13ms/step
Epoch 3/100
1/1 - 0s - loss: 0.6927 - acc: 0.4000 - 12ms/epoch - 12ms/step
Epoch 4/100
1/1 - 0s - loss: 0.6921 - acc: 0.7000 - 12ms/epoch - 12ms/step
Epoch 5/100
1/1 - 0s - loss: 0.6916 - acc: 0.7000 - 12ms/epoch - 12ms/step
Epoch 6/100
1/1 - 0s - loss: 0.6918 - acc: 0.7000 - 21ms/epoch - 21ms/step
Epoch 7/100
1/1 - 0s - loss: 0.6917 - acc: 0.8000 - 11ms/epoch - 11ms/step
Epoch 8/100
1/1 - 0s - loss: 0.6920 - acc: 0.7000 - 12ms/epoch - 12ms/step
Epoch 9/100
1/1 - 0s - loss: 0.6907 - acc: 0.8000 - 13ms/epoch - 13ms/step
Epoch 10/100
1/1 - 0s - loss: 0.6917 - acc: 0.7000 - 11ms/epoch - 11ms/step
Epoch 11/100
1/1 - 0s - loss: 0.6896 - acc: 0.8000 - 13ms/epoch - 13ms/step
Epoch 12/100
1/1 - 0s - loss: 0.6904 - acc: 0.8000 - 12ms/epoch - 12ms/step
Epoch 13/100
1/1 - 0s - loss: 0.6894 - acc: 0.8000 - 13ms/epoch - 13ms/step
Epoch 14/100
1/1 - 0s - l

In [7]:
print(embedding_layer.get_weights()[0].shape)

(50, 8)


In [8]:
print(model.predict(padded_reviews)[3])

1/1 [==============================] - 0s 293ms/step
[0.9952038]


In [ ]:
print(model.predict(padded_reviews)[3])

1/1 [==============================] - 0s 25ms/step
[0.98601276]
